#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# Customize to your needs...
alias dev="cd /Users/benhalton/dev/projects"
alias gomongo="cd $MONGO_HOME"
alias tools="cd /Users/benhalton/tools/"
alias ll="ls -laG"
alias gst="git status"
alias gca="git commit -a -m"
alias editpath="vim ~/.zprofile"
alias undolastcommit="git reset --soft HEAD~1"
alias whereisjava="ll `which java`"
alias addalias="vim ~/.zprezto/runcoms/zshrc"

